### ISSUE TITLE
Tacotron: Detect sentence ending explicitly instead of thresholding

### ISSUE THREAD

**Issue by reuben** [mozilla/TTS#10]

**Comment by erogol** [comment]
This should be done easily by inferring the attention alignment vector since in general after the end of the sentence, alignment gets awkward as below. Maybe adding a FC layer prediction stop token would work or a smart way of post processing (If smart enough).

Other implementations solve this by predicting the zero paddings. However until now we used masked loss and avoid the zero paddings for the sake of larger batch training and stable optimization.

![attention_skewed](https://user-images.githubusercontent.com/1402048/38569798-8e6a6cf0-3cec-11e8-9b28-740905004894.png)

**Comment by erogol** [comment]
Last commit uses a different thresholding with a heuristic. It seems working on most the cases but still I favor explicit prediction.

**Comment by erogol** [comment]
Done ! What I've done is predicting a stop token for each prediction of ```r``` frames. So instead of predicting a single stop token for each mel-frame, it is more efficient and successful implementation. An example is below. The plot shows the stop token prediction confidence after the sigmoid unit. 

![index](https://user-images.githubusercontent.com/1402048/39577407-936f2ebe-4ee1-11e8-86f3-2a4fcc9e8808.png)
