### ISSUE TITLE
Audio generation time is about 2 seconds

### ISSUE THREAD

**Issue by tsungruihon** [mozilla/TTS#114]
thanks to @erogol , it seems that the model `(93k step)` performs well. But when i use `notebooks/Benchmark.ipynb` to test the checkpoint model, the audio generation time is about 2 seconds given the sentence like `xiao3 yang4 er2`, which is pretty slow and could not use it in production environment. 

Could anyone give me a hint ? Or did i do something wrong ?

**Comment by tsungruihon** [comment]
And the most wired thing is that when i changed to use GPU to generate audio, the gpu time is not much faster than the cpu time.

**Comment by erogol** [comment]
@tsungruihon try to reduce the number of iterations for griffin-lim. It is set in config.json or you can explicitly set for AudioProcessor ```"griffin_lim_iters": 60,```

@tsungruihon GPU is not much faster because you give only one instance and the bottleneck is the GL algorithm not the network in a normal CPU.

It is also important how long does it take to say ```xiao3 yang4 er2```. If the supposed audio length is comparable with the model execution time, then it is still close to real-time.

One optimization would be to generate voice as decoder goes along, instead of waiting for the whole decoder loop. However, it needs a hand to deal with.

**Comment by tsungruihon** [comment]
@erogol thanks erogol, does the vocoder changed to `world` vocoder would make audio generation time shorter?

**Comment by erogol** [comment]
@tsungruihon I attempted but I've not tried the whole way.

**Comment by tsungruihon** [comment]
@erogol  i have saw the branch `world-new`, that's a fantastic work.

**Comment by tsungruihon** [comment]
@erogol I would like to try `WaveRNN`, should i focus on the `master` branch or `mulaw` branch under the link `https://github.com/erogol/WaveRNN` ?

**Comment by erogol** [comment]
@tsungruihon you should go for distribute branch. But it is not documented yet, so you need a bit of code reading to understand how it works.

**Comment by tsungruihon** [comment]
@erogol  i see. Thanks erogol.

**Comment by tsungruihon** [comment]
@erogol how could i generate audio using your `wavernn` code under `distribute branch`? I noticed that there is a `generate` function in `train.py` script but you haven't used it. Should i use that for synthetic audio ?

**Comment by erogol** [comment]
@tsungruihon check https://github.com/erogol/WaveRNN/tree/distribute/notebooks

**Comment by tsungruihon** [comment]
@erogol thanks erogol!! Can't wait to experiment !
