### ISSUE TITLE
Questions regarding non-latin language

### ISSUE THREAD

**Issue by jeewling** [mozilla/TTS#137]
Hi, thank for sharing this amazing work. I want to train the model on Thai language dataset. So I have some questions about non-latin language support such as Thai.
- What additional steps to do beside create a custom adapter in `preprocess.py`? Do I have to change some codes in `utils/text`? And what else I need to do to start training.
- Do I have to do forced alignment on the data?

Thanks in advance!

**Comment by erogol** [comment]
@jeewling 

If the language is supported here you can train by just changing the corresponding config.json language field and train with phonemes. Otherwise, you need to introduce your own character set to symbols.py and train with raw characters.

It depends. If the performance is low, you should try to enforce the alignment.

**Comment by jeewling** [comment]
@erogol Thank for the reply. Fortunately, the language is supported by epitran but not phonemizer one. So do I just use epitran for phonemizing the texts, change language field in `config.json` and then train with phonemes ? If yes what is the value of `phoneme_language` field to change for ?

**Comment by erogol** [comment]
@jeewling TTS does not work with epitran at the moment. You need to inject your own code. phoneme_language defines the language of phonemizer nothing more. So if you change to epitran use and set it as it is necessary.
