### ISSUE TITLE
customize maximum audio length (duration) ?

### ISSUE THREAD

**Issue by MuruganR96** [mozilla/TTS#171]
sir i was tested (server) my text by using latest pre-trained model. 
inference audio reached up to 12 sec. but not covered some text at the end.

is it problem in the text or it reached it max length?

the missing words only pass as text, it is working fine.

how to customize maximum audio length (duration) ?

Thanks Mozila TTS Team.

**Comment by erogol** [comment]
It might be related about the attention part of the network. I'd use the benchmark notebook to see the attention alignment on the same text. Unfortunately, pre-trained model needs to be trained some more to be more decent and sometimes it misses some parts. You can also try to enable attention windowing for more resillient results.

In theory, the length of the voice is limited by the GPU memory if you use CUDA otherwise CPU memory.
