### ISSUE TITLE
extract features - some options broken

### ISSUE THREAD

**Issue by twerkmeister** [mozilla/TTS#176]
Hey @erogol, while implementing the multi speaker embeddings, I was wrapping my head around the processors, dataset, and caching to make sure behavior is consistent. Along the way I was about to do some small refactorings, especially on the extract features script. 

Then I noticed it had some bugs, and was wondering what parts of the caching are still being used and relevant? If so I would fix and refactor it, otherwise we could drop some parts and simplify things. Here are the lines in question:

https://github.com/mozilla/TTS/blob/2e8446539fef72a4bcaa8e3e6a19283a23c186be/extract_features.py#L65-L80

both options `args.only_mel` and `args.process_audio` are problematic. 

1. `args.only_mel` leads to no linear spectrogram being produced. But the dataset always assumes the linear spectrogram being on third position if it is dealing with a cached item ...
https://github.com/mozilla/TTS/blob/2e8446539fef72a4bcaa8e3e6a19283a23c186be/datasets/TTSDataset.py#L116-L127
so with `args.only_mel` true it would try to load the len of the wav array as a file...

2. `args.process_audio` deletes `output[0]` which is the text, and then inserts the .npy file at position 1. So the resulting output array would look like `[/path/to/wav, /path/to/npy, ....]` with the text gone.

What parts of the caching are still relevant? And does it come with a significant speed increase overall?

**Comment by erogol** [comment]
For my use extract_features is deprecated. I don't think it is also compatible anymore with the dataloader. 

Some questions to follow up the discussion:

- Do you think it is relevant for your case? If so, why ?
- My preference is to use the first epoch of the dataloader to cache the files. You can see the implementation for the phoneme computation in TTSDataset.py. I decided that way since caching files with a separate script puts an additional mental burden for me to run multiple experiments.

But of course, if people find it useful, it is better to keep it.

**Comment by twerkmeister** [comment]
Ah I see, good that I asked first. Otherwise I would've put effort in refactoring it. It's not relevant to me, but it would have needed to be adjusted to fit speaker embeddings. Given that it seems buggy currently and you are not using it either, I'd vote for dropping it altogether. If it's not a must-have it's good to delete it -> less to maintain.
