### ISSUE TITLE
Tacotron + WaveRNN experiments

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#212]
Following #26, I try to combine Tacotron with WaveRNN for faster training/inference. 

The idea is to predict the linear spectrogram with Tacotron and project it back to mel-spectrogram algorithmically. Use this projected specs to train WaveRNN. 

**Update:**
So far, I am able to make things work with WaveRNN + mulaw and Tacotron. However, it is lower in quality than Tacotron2. Tacotron needs a finer way to generate mel-spectrograms. It is emprically ~2 times worse (loss values) than Tacotron2 in mel-spec syntehsis.

**Update:**
If you train WaveRNN by combining GT and Tacotron's spectrograms, the final result is on par with Tacotron2.

**Comment by geneing** [comment]
I don't quite understand why you would predict linear spectrogram and then project. Isn't mel-spectrogram available directly as an output of the decoder? 

It may be interesting to try using linear spectrogram as input to the WaveRNN - it may produce better quality sound since we'll be providing more data. However, it may have significant impact on vocoder performance.
