### ISSUE TITLE
Add Ethics Section / Considerations

### ISSUE THREAD

**Issue by PetrochukM** [mozilla/TTS#295]
This codebase could be used in a number of bad ways:

- This could be used for identity fraud. For example, TTS could have already been used to con someone out of money: https://www.wsj.com/articles/fraudsters-use-ai-to-mimic-ceos-voice-in-unusual-cybercrime-case-11567157402
- This could be used to fake political videos that could harm the democratic process and create a lot of confusion. This could potentially harm a presidential candidate.
- This could be used in a court of law to argue that the audio evidence is fake. For example, In a murder case the murderer could argue that the recording from the crime was generated by TTS; therefore, it cannot be used to convict.

Before this effort continues, there should be some ethical consideration that this work won't be used to harm another person, undermine government systems and undermine the legal system.

**The implications are large; therefore, it's important that there is serious thought put into the ethics of this open-source project. I'd recommend we invite and get advice from ethics experts to be safe.**

**Comment by PetrochukM** [comment]
@erogol What do you think? This should likely be considered before someone gets hurt :(

**Comment by kdavis-mozilla** [comment]
@PetrochukM What do you suggest to do?

**Comment by PetrochukM** [comment]
As the leading TTS code base, I think there is a great opprotunity to start defining what ethical TTS looks like! :) 

**Here's my suggestion**
Open source an analysis of the project ethics as a markdown or blog post. The analysis should cover the ethical implications of open source life-life TTS. Then, the analysis should be tied back to concrete development practices. Lastly, in order to validate the analysis, there should be some feedback from an expert in AI ethics. 

**Example**
A bad actor may want easy access to lifelike TTS to exploit senior citizens with automated phone calls. In order to mitigate that risk, Mozilla doesn't make trained TTS models accessible without going through a basic application system. Furthermore, Mozilla restricts the models from being used commercially. 

**Goal**
The goal is to mitigate the risk that the open-source TTS system is used to cause harm.

**Comment by PetrochukM** [comment]
Lastly, I'd consider adopting this oath: https://techcrunch.com/2018/03/14/a-hippocratic-oath-for-artificial-intelligence-practitioners/

Some of the principles:
> My AI will prevent harm whenever it can, for prevention is preferable to cure.

> I will apply, for the benefit of the humanity, all measures required, avoiding those twin traps of over-optimism and uniformed pessimism.

> I will remember that I remain a member of society, with special obligations to all my fellow human beings.

**Comment by nmstoker** [comment]
I appreciate the intention @PetrochukM but these misuses seem hard to defend against from within this repo or based on tying it to analysis, which the skeptic in me thinks may just slow down progress without discernible benefit. I think that the ethical discussion, important as it is, would be more suited to happen at another level and in a more general sense that is detached from this specific project (since the concerns are common to all TTS). Saying this, I'm merely giving personal opinions here and have no formal ethics experience.

If we take your two suggestions of making people go through an application process and restrictions commercial use, these would likely not deter someone motivated by the exploration of senior citizens. Someone who might proceed with that kind of scam will not be concerned about breaking commercial terms because it pales in comparison to the punishment relating to a scam. It would likely be hard to prove in any case. And only an application that severely impacted legitimate users would have the sort of teeth required to stop or slow down a bad actor.

That said, I'll try to keep an open mind and look forward to hearing what others have to say on this.

**Comment by erogol** [comment]
Pure personal comments. I think it is important to think about ethics of AI projects. However, placing a document about it is kind of futile. Since anyone with malice in mind, would not really read and care about it since the code is already there. 

Having user information before the code also hinders the progress. That would keep people using it away and issue some privacy concerns. We cant also really say anyone with the given info is secure to use TTS since it is really hard to verify the real identity. 

Being all said, I agree that we need a generic framework against malicious AI usage everywhere not only TTS.

**Comment by JRMeyer** [comment]
Documentation is futile to combat the evil-doers, but it may convince non-evil researchers be more thoughtful with the models they create / release. Something to the effect of `Don't use this code to do bad things` is easy enough to write into the `CODE_OF_CONDUCT`, right?

Not within the scope of this repo, but the only way to fight against malicious use of TTS is to develop technology which can discriminate synthetic speech from real speech, and have that technology embedded everywhere. It's the same issue with GPT-2.

**Comment by erogol** [comment]
@JRMeyer yeah we can write, but I don't think it will fand off people anyways. But it'd look good :)

**Comment by erogol** [comment]
https://github.com/mozilla/TTS/blob/master/CODE_OF_CONDUCT.md

**Comment by PetrochukM** [comment]
Can you please reopen this?

-----------------------

**Context:** The current thread has taken the first solution presented as the final solution. 
**Problem:** There is a significant risk for harm to other people; therefore,  there should be more time, more exploration, and more input taken on this issue.
**Potential Solution:** There should be a more thoughtful approach. For example, we could follow through on the points made in this graphic:
![image](https://user-images.githubusercontent.com/7424737/67814642-ca0afc00-fa61-11e9-9ce2-66ca5245b310.png)

Source: http://main.da.stanford.edu/

**Comment by erogol** [comment]
@PetrochukM you'r welcome to move it to https://discourse.mozilla.org/.

**Comment by PetrochukM** [comment]
Okay. Thanks for pointing me there. Do you think the forum will lead to a meaningful discussion of this serious issue?

@erogol As the main contributor to this, are you interested in putting in the time to critically think about this issue or is it not a priority?

**Comment by PetrochukM** [comment]
It sounds like this is not a priority issue... which is unfortunate given the significant negative impacts this open-source library could have. 

I'd encourage everyone on this thread to read this: https://twitter.com/metaviv/status/1205212076035080192?s=20

The article referenced in the tweet literally sums up the dominant viewpoint in this thread "I don't think it will fand off people anyways" @erogol:
![image](https://user-images.githubusercontent.com/7424737/70868600-1b4e4c80-1f37-11ea-8fcc-5d1548422950.png)

Please consider doing this, at the very least:
![image](https://user-images.githubusercontent.com/7424737/70868622-3a4cde80-1f37-11ea-8628-bdb3f138033b.png)

**Comment by m-toman** [comment]
I wonder how one could enforce the technical solutions in an open source project. You can't log what people do, the watermark code can just be removed, agreements ignored.

**Comment by nmstoker** [comment]
@PetrochukM I note you didn't raise this on the discussion board: https://discourse.mozilla.org/c/tts

As you appear to be involved with a commercial speech solution, maybe you could share some details on the discussion board regarding the AI Ethics approaches your company is considering?

Are you looking at updating your T&C and/or to implement any aspects of the points you raise and how do you see these working in an open source solution?

Do you see any conflict with a commercial software operator suggesting open source projects apply restrictions?

**Comment by PetrochukM** [comment]
@m-toman There are some initial first steps, for example:

1. At the moment, the voice actors used in this repository did not consent to have their voice cloned. For example, I haven't been able to find any consent that "Linda Johnson" gave for her voice to be cloned. 
2. There could be a basic vetting system for downloading pre-trained models. 

I also don't want to be the only person thinking of solutions. If possible, I'd like some help...

**Comment by PetrochukM** [comment]
> My AI will prevent harm whenever it can, for prevention is preferable to cure.
https://techcrunch.com/2018/03/14/a-hippocratic-oath-for-artificial-intelligence-practitioners/

At the end of the day, I don't expect the people here to solve the world's problems. There are basic things that we can do to at least mitigate potential misuse of this technology.

**Comment by nmstoker** [comment]
My apologies, wasn't meant to come across as interrogation, i thought you'd be willing to bring relevant experiences to the discussion but I appreciate if you prefer not to. Btw: no digging required, it's on your profile here.

**Comment by reuben** [comment]
@PetrochukM I think you are severely underestimating the complexity of this problem. Your suggestions proposed here:
1. Misunderstand how licensing works ("Linda Johnson did not consent to voice cloning"), or 
2. Assume licensing issues can be fixed by engineering rather than lawyers (adding counter measures in an MPL project), or
3. Would require relicensing the project *and* would make it no longer open source (user vetting, usage restrictions).

In addition, they would completely derail the focus of this project, which is to implement a high quality open source text-to-speech engine, into solving the general problem of ethical licensing of software and machine learning models.

This discussion is better suited for the Open Source Initiative forums, or the Electronic Frontier Foundation forums, or the Mozilla Governance forum. Not the TTS issue tracker.

**Comment by PetrochukM** [comment]
It sounds like you want to derail this ethics discussion by incorporating more process and more stakeholders. 

The changes I proposed above are simple and don't require lawyers...

1. Ask for consent from a voice actor from cloning their voice. A simple "Yes" via an email exchange is more than enough.
2. Having a simple vetting process before a user can get ahold of a pre-trained model. For example, the vetting process could be like... "Please email erogol@mozill.com for a link to the pre-trained model with your Linkedin and Facebook".

@reuben I am actually doing something about this issue by bringing it up. It's easy to be a naysayer. It's hard to come up with solutions!

**Comment by reuben** [comment]
> Ask for consent from a voice actor from cloning their voice. A simple "Yes" via an email exchange is more than enough.

This is not a solution to anything. We already have consent from voice actors through contracts and licenses. It doesn't change anything for someone using this code on their own, as we don't have control over that due to the MPL license of this code.

> 2. Having a simple vetting process before a user can get ahold of a pre-trained model. For example, the vetting process could be like... "Please email erogol for a Google Drive link to the pre-trained model with your Linkedin and Facebook".

This also doesn't fix anything, due to the MPL license of the pre-trained models. Anyone who gets somehow "vetted" (by checking their LinkedIn? wtf) is free to then redistribute the model without any vetting themselves.

**Comment by PetrochukM** [comment]
> This is not a solution to anything. We already have consent from voice actors through contracts and licenses. It doesn't change anything for someone using this code on their own, as we don't have control over that due to the MPL license of this code.

Actually? Sorry, I looked for an hour for the contract or agreement with Linda Johnson (https://keithito.com/LJ-Speech-Dataset/). I'd love to see it! 

I stopped working with Linda Johnson dataset because I couldn't find any evidence that she/he provided consent for her likeness to be used. 

> This also doesn't fix anything, due to the MPL license of the pre-trained models. Anyone who gets somehow "vetted" (by checking their LinkedIn? wtf) is free to then redistribute the model without any vetting themselves.

Are you seriously saying that checking someone's Linkedin doesn't fix "anything"? The language sounds devoid of nuance... 

It reads as if you are trivializing all the pain and anguish that deep fakes have already caused in our society.

**Comment by reuben** [comment]
> Actually? Sorry, I looked for an hour for the contract or agreement with Linda Johnson (https://keithito.com/LJ-Speech-Dataset/). I'd love to see it!

It is the first sentence after the title, as well as the last sentence of the second paragraph. Linda Johnson licensed their voice recordings into the public domain when contributing to Librivox.

> This language sounds devoid of nuance saying things like "anything" and "wtf"...

It *is* devoid of nuance. I don't think this issue will accomplish anything beyond wasting project resources. It is already closed. I have given examples of places where this can be discussed with the appropriate nuance (legal/licensing/governance forums), and where it actually has a chance of going anywhere. Please stop commenting here as if this complex issue is simply a matter of adopting some bullet point list of ideas. Specially after the issue has already been closed.

**Comment by PetrochukM** [comment]
Licensing voice recordings is different than licensing your likeness... If you create an audio book, that doesn't mean you are giving permission for everyone to clone your voice. 

--------

I am disappointed that deep fakes have caused real problems. Yet, it seems like @reuben is advocating for not doing anything. 

This simple step that I started the discussion with was not even entertained...

> The implications are large; therefore, it's important that there is serious thought put into the ethics of this open-source project. I'd recommend we invite and get advice from ethics experts to be safe.

**Comment by reuben** [comment]
> Can you help me navigate the various legal/licensing/governance forums?

I would start by creating a thread on the Mozilla Governance mailing list about how to deal with ethical restrictions in MPL licensed projects. First you probably should read up on software licensing. As I've said here multiple times, you are completely ignoring the licensing issue which is at the core of this problem.

You can describe the problem of ML abuse/deep fakes, and how Open Source licenses do not permit things like usage restrictions or user vetting. You'll then hopefully get some feedback from people who know about software licensing and can help set guidelines for existing and future Mozilla projects.

As for the technical
