### ISSUE TITLE
New FAQ page. Waiting for your reviews.

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#335]
I laid out a FAQ [page](https://github.com/mozilla/TTS/wiki/FAQ). Please let me know your comments.

**Comment by ntsourakis** [comment]
Really helpful. Thank you. Some explanation on the tensorboard output would be also helpful.
Is it possible to share a sample training for comparing inside tensorboard?

**Comment by erogol** [comment]
@ntsourakis just did that. Please check the last part.

**Comment by ntsourakis** [comment]
That helps a lot. I don't see the "Image" tab in my tensorboard though. Only Scalars + Audio.

**Comment by erogol** [comment]
If you are training TTS there must be an Image tab.

**Comment by ntsourakis** [comment]
I am working with Albanian and for step 2, I need to create the alphabet. There are elements written with two letters like 'Dh' and 'Gj'. How should one change the _characters in utils.text.symbols?

**Comment by erogol** [comment]
You need to add them there as the other characters

**Comment by ntsourakis** [comment]
Okay, so it's actually characters and not alphabet. 

The letters in the Albanian alphabet (where the same symbol can appear multiple times):

A	B	C	Ç	D	Dh	E	Ë	F	G	Gj	H	I	J	K	L	Ll	M	N	Nj	O	P	Q	R	Rr	S	Sh	T	Th	U	V	X	Xh	Y	Z	Zh
a	b	c	ç	d	dh	e	ë	f	g	gj	h	i	j	k	l	ll	m	n	nj	o	p	q	r	rr	s	sh	t	th	u	v	x	xh	y	z	zh

become:

ABCÇDEËFGHIJKLMNOPQRSTUVXYZabcçdefghijklmnopqrstuvxyz

**Comment by nmstoker** [comment]
My FAQ feedback:

- generally I think it looks good and will help

- ordering them and grouping similar items could be helpful

  There's probably no "*optimal order*" but I'd consider the one about "**a bunch of errors**" going at the top: it needs to catch the eye of potentially less diligent, experienced people

  then "**how do I choose which model**" and other questions that deal with initial decisions / steps

  and then finally a block for all the training related ones

- Might be worth renaming that "a bunch of errors" one so that it puts **errors** right near the front of the sentence, something like "**Errors occurring with pre-trained model. How can I resolve them?**"

- This is easier said than done, but finding someone averagely computer literate with Python but who doesn't know about TTS and asking them to read through the answers and explain what they think is easy to follow would help (people who've seen/used the project can easily miss what's hard to understand, especially as things change over time)

- Possibly consider a few questions on what not to do (or at least that's ill advised) and around expectation mgt (eg for people who might not realise that an hour of audio wouldn't typically be feasible)

I'm AFK right now (🤒🛌) but I'll give it more thought once I'm better, esp. my last point.

**Comment by erogol** [comment]
@nmstoker I agree on all of your comments. I reordered and rephrased things as you suggested as starters. And get better soon !
