### ISSUE TITLE
Min DB and Ref DB

### ISSUE THREAD

**Issue by PetrochukM** [mozilla/TTS#36]
Neither the Tacotron 2 or Tacotron paper mentioned anything about any decibel normalization, can you help me understand why this is necessary?

Relevant config:
```
 "min_level_db": -100,
  "ref_level_db": 20,
```

**Comment by erogol** [comment]
The reason is to limit the data norm into 0-1 for training and keeping all denormalized db values negative. You might prefer only to apply log normalization but with this  scheme things are slightly better.

**Comment by PetrochukM** [comment]
Thank you! 

Yeah, the Tacotron 2 paper and the WaveRNN paper only do log normalization and dynamic range compression.

Can you give me some intuition about how these values are chosen? Do they need to updated per dataset?

**Comment by erogol** [comment]
Probably yes, you need to fit for the each dataset. How I find good values is based on plotting the spectrograms and check whether it is descriptive and free from noise. 

However, I've never tried without with these additional preprocessing steps. It might be true that log+compression is enough. Maybe you can help me to try ;).

**Comment by PetrochukM** [comment]
@erogol I do not have your code running without them. But I do have a private Tacotron 2 implementation without these steps, it seems fine. 

I do not have a good method for evaluating the difference it makes.

**Comment by erogol** [comment]
Yeap you are right, however if you don't expose the structure in the data then the network cannot see it and does not learn it. That's why these preprocessing steps are useful. However, I need to experiment the the peeled version before saying something sure.

**Comment by erogol** [comment]
I'll run the experiment soon and report here.

**Comment by PetrochukM** [comment]
@erogol Thank you!

**Comment by erogol** [comment]
As far as I can tell these two values are importatn to train the network. Without these two I was not even able to align the attention. 

My feeling is that they are necessary to, first, normalize the spec values in range [0, 1] and we need ref_level_db to shift the silent part of the signal to 0 so that applied padding all through the network would make sense and it also enables network to learn the silent parts easily. That is also why the attention had hard times without these two parameters.
