### ISSUE TITLE
Does anyone have any reasonable intutition about the right way to normalize spectrograms in TTS training?

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#377]
So there are different TTS libraries out there and I see they all use different normalization methods for spectrogram normalization in model training. 

Right now in Mozilla TTS what we do is the following;

- apply preemphasis to wav
- compute the spectrogram by stft
- ```audio.amp_to_db()``` -  convert amplitude to decibel with ```20 * np.log10(np.maximum(min_level, x))```
- ```audio._normalize()```  - normalize the spectrogram into the range [-4,4] assuming minimum db is -100

https://github.com/mozilla/TTS/blob/master/utils/audio.py#L151

First of all, does anyone see any problem here?

The only obvious thing above is that preemphasis operation is hard to recover if you do batch inference. There is no straight forward implementation of it in CUDA since de-preemphasis operation has a temporal dependency in itself.  Y
ou can approximate it by using RNN layers but it is slow. Hence, I guess it makes sense to drop preemphasis. This also makes our model incompatible with the latest vocoder models.

I see NVIDIA Tacotron implementation does not use any normalization except the amp_to_db operation

https://github.com/NVIDIA/tacotron2/blob/master/audio_processing.py#L78

ESPNet, on the other hand, uses Standardization with mean and variance. It is good to compute normalization parameters from the target dataset (as in image recognition) to make the normalization flexible among different datasets. However, the downside is that each frequency level attains the same level of consideration by the model. I don't think it is the right thing to do since for speech different frequency levels signify different aspects of the speech. Another downside is that in a multi-speaker model we need to compute mean-var stats separately per speaker. Which is a viable but an additional headache.

Also, I saw that using Standardization enables better vocoder models, especially with the new GAN based models.

I also started to experiment with Standardization and saw that the training seems more stable but the GL based results sound worse.

So I guess the better option is to use Standardization with a trained vocoder and our current normalization flow for GL.

These are all I know and I am kind of confused here. Please let me know if you have any take in this issue.

**Comment by PetrochukM** [comment]
Here are two things that come to mind:

**dbFS instead of dB**
I'd recommend using [dBFS](https://en.wikipedia.org/wiki/DBFS). The maximum decibel is set relative to the full scale which is a full-scale square wave of 997 Hz. The minimum decibel should be around -100 dBFS to -150 dBFS which represents the quietest sound a human can hear.

**Sone instead of dB**
Furthermore, there are other things to consider. I'd consider using the [Sone](https://en.wikipedia.org/wiki/Sone) scale instead of the dB scale because it scales linearly with perceived loudness; therefore, it'd make sense to use with a linear loss. For context, the perceived loudness doubles every +10 dB; therefore, it's not a linear representation of loudness.

**Comment by erogol** [comment]
@PetrochukM what we compute right now is I guess already dBFS.
