### ISSUE TITLE
special format of waveform?

### ISSUE THREAD

**Issue by mit10000** [mozilla/TTS#465]
On Ubuntu 16.04
If I directly use synthesize.py and save the waveform to a xyz.wav file, then use aplay xyz.wav to play, sounds are normal.

If I try to directly play waveform (which is a numpy array) by using

import pyaudio
pa = pyaudio.PyAudio()
stream = pa.open(format=pa.get_format_from_width(4),channels=1,rate=22050,output=True)
stream.write(waveform)

The played sound is just noise, could anyone help? Thanks.

**Comment by nmstoker** [comment]
This is off-topic as it's not related to TTS and instead about your difficulties with [PyAudio](https://people.csail.mit.edu/hubert/pyaudio/docs/)

However as I think I can explain the solution for you, I'll have a crack at answering. I suggest that you close the issue whether it works or not (and if my solution doesn't work for you, Google should help! :slightly_smiling_face: )

When you play the file xyz.wav with aplay, you should see it correctly identify the number of bits for the recording.  If you got the audio from TTS, then it's likely saying the audio is _16 bit_ with output something like this:

    Playing WAVE 'xyz.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono



In light of that, your use of "4" in pa.get_format_from_width(**4**) is going to cause problems because that gives 4 bytes, ie 32 bits, which will break the audio up incorrectly and unsurprisingly will cause noise as output (depending on the file you may be able to make out some of the voice - I tried it on my computer to verify switching to 2 worked as expected and when I tried it at 4 it was _just_ recognisable as voice audio but was clearly corrupted).

Some more general background here: http://sites.music.columbia.edu/cmc/MusicAndComputers/chapter2/02_05.php#:~:text=The%20number%20of%20bits%20used,digital%20recording%20and%20synthesis%20systems.

Hope that helps!
