### ISSUE TITLE
SpeakerEmbedding

### ISSUE THREAD

**Issue by byebye1** [mozilla/TTS#552]
Hello!
Where can I find notebook from Wiki Speaker Encoder!
When I click on the link, I get 404 note found 

![2020-10-27 20 08 54](https://user-images.githubusercontent.com/45552093/97336631-46f8cd80-1890-11eb-983e-e3d70570fc87.jpg)

**Comment by thorstenMueller** [comment]
Hey @byebye1 .
Project structure has been refactored in the past, so maybe wiki wasn't updated on the new new path.
@erogol Maybe you'd update wiki page (https://github.com/mozilla/TTS/wiki/Speaker-Encoder).

In the meantime maybe this is helpful:
* OLD:		https://github.com/mozilla/TTS/tree/dev/speaker_encoder
* NEW:	https://github.com/mozilla/TTS/tree/dev/TTS/speaker_encoder

I’m unsure if the specific requested notebook is still available but you can take a look here (https://github.com/mozilla/TTS/tree/dev/notebooks) because there are some notebooks on „speaker encoder“ topics available.

**Comment by thorstenMueller** [comment]
It seems that @lstolcman and @erogol are magicans or mindreader because your requested notebook suddenly appeared again :-).
See following PR for details: https://github.com/mozilla/TTS/pull/554

**Comment by byebye1** [comment]
> It seems that @lstolcman and @erogol are magicans or mindreader because your requested notebook suddenly appeared again :-).
> See following PR for details: #554

Thank you!
