### ISSUE TITLE
UnicodeDecodeError:

### ISSUE THREAD

**Issue by Azagthothz** [mozilla/TTS#648]
Hi. I'm using Python 3.8.7 on Win10. I tried this in cmd:

C:\Program1\TTS-master>tts --text "say something"    --model_name "tts_models/en/ljspeech/glow-tts"    --vocoder_name "vocoder_models/universal/libri-tts/wavegrad"    --out_path out

I got this error: 

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3230: character maps to <undefined>

The "position" seems to vary based on the model_name like so:

tts_models/en/ljspeech/glow-tts				3230
tts_models/en/ljspeech/tacotron2-DCA			3000
tts_models/en/ljspeech/speedy-speech-wn		2907
tts_models/es/mai/tacotron2-DDC				3307
tts_models/fr/mai/tacotron2-DDC				3285

What is this and how can I fix it? I have no clue what I'm doing here so any help I can get is much appreciated. Thanks!

**Comment by erogol** [comment]
it happens under win10. I don't use windows so I don't know the answer. Hope someone with Win will help

**Comment by methane** [comment]
Try `set PYTHONUTF8=1` before executing tts.

**Comment by Isak-Andersson** [comment]
> Try `set PYTHONUTF8=1` before executing tts.

Yes, that worked. Thank you. Now I'm getting some other errors tho. 

glow-tts gives:
RuntimeError: espeak not installed on your system

tacotron2 gives:
FileNotFoundError: [Errno 2] No such file or directory: './scale_stats.npy'

speedy-speech-wn gives:
FileNotFoundError: [Errno 2] No such file or directory: '/root/LJSpeech-1.1/scale_stats.npy'

**Comment by anotherdirtbag** [comment]
also running win 10. for the scale_stats.npy errors, i had to go find config.json and change the stats_path to the absolute path with escaped backslashes \\
may not the same for you but the files were both in here for me
C:\Users\<username>\AppData\Local\tts\tts_models--en--ljspeech--tacotron2-DCA

**Comment by anotherdirtbag** [comment]
again from win10. I installed espeak using cygwin. no idea if the sourceforge one is safe or the right thing.

**Comment by Isak-Andersson** [comment]
> I installed espeak using cygwin.

Yeah, this fixed glow-tts. It seems to work now. 

tacotron2 and speedy-speech-wn now both gives:
FileNotFoundError: [Errno 2] No such file or directory: '/root/LJSpeech-1.1/scale_stats.npy'

Guess I have to add the absolute path to /root/LJSpeech-1.1/scale_stats.npy as well. But in what file and which parameter? Feel like I'm grasping at straws here...

**Comment by anotherdirtbag** [comment]
That's exactly what you have to do.
I'm willing to help a little more. Open a cmd window and run 
`cd C:/Users && dir /s /b | findstr "tts\\.*\\config.json"`
one or more of those files will have '/root/LJSpeech-1.1/scale_stats.npy' inside. replace that with the absolute path to the scale_stats.npy in the same folder as that config.json. and note that \\ needs to be \\\\

**Comment by jaspermolgvits** [comment]
Hey guys! I'm having the exact same issue...
@Azagthothz, did you figure it out?

> That's exactly what you have to do.
> I'm willing to help a little more. Open a cmd window and run
> `cd C:/Users && dir /s /b | findstr "tts\\.*\\config.json"`
> one or more of those files will have '/root/LJSpeech-1.1/scale_stats.npy' inside. replace that with the absolute path to the scale_stats.npy in the same folder as that config.json. and note that \ needs to be \\

@anotherdirtbag, the cmd command only returns one config file in TTS/tts/configs and it doesn't contain any reference to `/root/LJSpeech-1.1/scale_stats.npy`, only to `/home/erogol/Data/LJSpeech-1.1/scale_stats.npy` and pointing that value to another path still results in `No such file or directory: '/root/LJSpeech-1.1/scale_stats.npy'`.

**Comment by AlyoshaVasilieva** [comment]
Necessary steps for me:

1. `set PYTHONUTF8=1`
2. Try to run TTS, such as `tts --text "Hello world." --model_name tts_models/en/ljspeech/tacotron2-DCA` . This triggers model download but will fail to actually run.
3. In file `C:\Users\ME\AppData\Local\tts\tts_models--en--ljspeech--tacotron2-DCA\config.json` change two paths:
   1. `"path": "/root/LJSpeech-1.1/"` to `"path": "C:\\Users\\ME\\AppData\\Local\\tts\\tts_models--en--ljspeech--tacotron2-DCA"`
   2. `"stats_path": "/root/LJSpeech-1.1/scale_stats.npy"` to `"stats_path": "C:\\Users\\ME\\AppData\\Local\\tts\\tts_models--en--ljspeech--tacotron2-DCA\\scale_stats.npy"`
4. Install eSpeak NG from https://github.com/espeak-ng/espeak-ng/releases
5. Set environment variable `PHONEMIZER_ESPEAK_PATH` to `C:\Program Files\eSpeak NG\espeak-ng.exe`. For example, `set PHONEMIZER_ESPEAK_PATH=C:\Program Files\eSpeak NG\espeak-ng.exe` in cmd. Quoting the path is not only unnecessary but will cause this step to fail.

**Comment by slaviboy** [comment]
After I have done everything specified by @AlyoshaVasilieva, now I have an error:
```
raise ValueError(f" [!] Language {language} is not supported for phonemization.")
ValueError:  [!] Language en-us is not supported for phonemization.
```
I am using  Windows 10, 64-bit version. I think it has something to do with eSpeak, although it was already installed, I think it is not detected somehow! Any idea how to fix it?

***

**Today I have installed the latest release "Linux Mint 20.1", and I can confirm that the TTS is working with python3.8. But on Windows 10, I am still not able to fix the problem!**

**Comment by slaviboy** [comment]
When I wanted to test some of the old model on my Linux system, it said that the TTS version should be <=v0.0.13, so I have downloaded the older version from the [releases](https://github.com/coqui-ai/TTS/releases). But then I got the same error I had in Windows **_ValueError:  [!] Language en-us is not supported for phonemization._**, then I saw that he removed phonemizer support due to license conflict.

So then I went back on my Windows10 machine, and I manage to run the TTS, it seems that I was using old model, and that is why I got that error. Here is the full explanation (How to run TTS on Windows10, 64-bit)
***

_!! Change Slaviboy with your windows username (C:\Users\Slaviboy\..  => C:\Users\Your_Username!!_
1) Install python version < 3.8  (mine was Python 3.8.7) from here https://www.python.org/downloads/
3) Install **_pip_**
4) Go to C:\Users\Slaviboy\AppData\Local\tts\   and delete everything from there, in case you have downloaded some older models
5) Download the latest TTS version as Zip, at the time I am writing this it is [v0.0.15.1](https://github.com/coqui-ai/TTS/releases).
6) Extract the Zip file on your desktop
7) Open Cmd or PowerShell as administrator
     - Press 'Start' windows button
     - Type in PowerShell
     - Right click on it and then 'Run as administrator'
     
8) Now go to the ..TTS\bin\ directory where you have extracted the Zip file by typing
     >  **_cd C:\Users\Slaviboy\Desktop\TTS-0.0.15.1\TTS-0.0.15.1\TTS\bin_**
     
9) Now type in
     > **_python synthesize.py --text "Text for TTS" --model_name "tts_models/en/ljspeech/tacotron2-DDC" --out_path C:/output.wav_**
     
8) Wait for the model to download, and run the same command again!

***

There is no need to install eSpeak, if you use the **tacotron2-DDC** model, and there is no need to change the config.json file.
