### ISSUE TITLE
Need Complete Documentation

### ISSUE THREAD

**Issue by sheikhma3** [mozilla/TTS#74]
I need complete documentation of code for understanding and to train it for different languages. Can you Provide me the documentation?

**Comment by erogol** [comment]
There is not documentation hitherto since things are not yet so stable to be documented. But yes eventually, we need one. 

But training a new model is quite easy. You need to write a new adaptor in datasets/preprocess.py that loads your metadata.txt and converts it compatible with TTS. You better use dev branch for this.

**Comment by sheikhma3** [comment]
Sure but i need to change the code in util.text. Want to know about functions written over there. I need to change everything over there

**Comment by erogol** [comment]
I don't know what is that you want to do exactly. If you tell me more, I can guide you. I assume you like to train on a new language. If it is the case, you just need to update 'utils/text/symbols.py'.
