### ISSUE TITLE
A new Notebook to find best Audio parameter for a dataset.

### ISSUE THREAD

**Issue by erogol** [mozilla/TTS#99]
Create a Jupyter Notebook to help you to find the best audio parameters in a controlled manner.

**Comment by erogol** [comment]
done https://github.com/mozilla/TTS/blob/dev/notebooks/CheckSpectrograms.ipynb

**Comment by mazzzystar** [comment]
@erogol 
Thanks for the script, but how could we measure which parameter is better ?  Only by looking the spectrogram or wave figure ?  

I'd like to compare the parameter by calculating the distance between `wav` and `wav_gen` in `compare_values` function. But I found **these two sequence have different length**, I guess it could because the inverse STFT windows mismatch, now I need to compare two different length sequence. Here I tried 3 methods:

* Crop `wav` to have the same length with `wav_gen`
```python
dist = np.sum(abs(wav_gen - wav[:len(wav_gen)]))
```
* Moving windows to get the `MIN` distance between every `wav_gen` and `wav`
```python
MIN_DIST = 10000
for i in range(len(wav) - len(wav_gen)):
    dist = np.sum(abs(wav_gen - wav[i : i+len(wav_gen)]))
    if dist < MIN_DIST:
        MIN_DIST = dist
```

* [Dynamic time warping](https://en.wikipedia.org/wiki/Dynamic_time_warping)

* [Cross-correlation](https://en.wikipedia.org/wiki/Cross-correlation)

Which method do you think the best to compare the similarity ?

**Comment by erogol** [comment]
@mazzzystar based on STFT parameters, it applies kindda padding. I believe this might lead to a mismatch.

How I personally compare signals is more visual and auditory. I basically synthesize a voice and compare with the reference. Better the sound, better the parameters. I also check the wave signals visually, if they match good enough.

I don't really try to compute a certain value comparing two signals since things with better values do not directly mean more intelligible.

If you really like to compare two signals mathematically, there are ways even if they differ in length. I don't remember on top of my head but a simple search would reveal what they are.

**Comment by erogol** [comment]
@mazzzystar they are comparable to my ear. If you like to get rid of hizzy effect at the background you might try ```preemhapsis: 0"

**Comment by mazzzystar** [comment]
@erogol OK, I'll try out and give you feedback.

**Comment by wjqkkky** [comment]
Hi @erogol , `CheckSpectrograms.ipynb` has lost or been deleted. Where can I find it? Thanks!
